config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  resources :tools do
    resources :bookings, only: [:new, :create]
  end

  resources :tools, only: [:destroy]

  resources :bookings, only: [:show, :index] do
    resources :reviews, only: [:create]
  end

  resources :users, only: [:show, :index, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :reviews, dependent: :destroy
  belongs_to :user
  belongs_to :tool
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :content, length: { maximum: 40 }
end

app/models/tool.rb
class Tool < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  belongs_to :user
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  include PgSearch::Model
  # multisearchable against: [:name, :description, :address]
  pg_search_scope :search_by_name,
    against: [:name, :description, :address, :category],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tools
  has_many :bookings
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
    @tool = Tool.find(params[:tool_id])
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.tool = Tool.find(params[:tool_id])
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking), notice: "booking was successfully added"
    else
      render :new
    end
  end

  def index
    @user = current_user
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end

  def show
    @review = Review.new
    @booking = Booking.find(params[:id])
    @tool_owner = User.find(@booking.user_id)
    authorize @booking
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :tool_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @tool = Tool.find(params[:tool_id])
    @review = Review.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    authorize @review
    if @review.save
      redirect_to booking_path(@booking)
    else
      render 'bookings/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @tools = policy_scope(Tool).order(created_at: :desc)
     # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    if params[:query].present?
      @tools = Tool.search_by_name(params[:query])
    else
      @tools = Tool.all
    end
    @markers = @tools.geocoded.map do |tool|
     {
      lat: tool.latitude,
      lng: tool.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { tool: tool })
     }
    end
  end

  def show
    @booking = Booking.new
    @tool = Tool.find(params[:id])
    authorize @tool
    @marker = [{lat: @tool.latitude,
                lng: @tool.longitude}
              ]
  end

  def new
    @tool = Tool.new
    authorize @tool
  end

  def create
    @tool = Tool.new(tool_params)
    @tool.user = current_user
    authorize @tool
    if @tool.save
      redirect_to @tool, notice: "Tool was successfully added"
    else
      render :new
    end
  end

  def destroy
    @tool = Tool.find(params[:id])
    authorize @tool
    @tool.destroy
    redirect_to user_path(current_user)
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def tool_params
    params.require(:tool).permit(:name, :category, :description, :user_id, :address, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def edit
    @user = current_user
    authorize @user
  end

  def update
    @user = current_user
    authorize @user
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:photo, :first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/index.html.erb
<div class="screen">
  <h2 class="mb-5">your booked tools are here</h2>

  <div class="card-bookings mb-5 mt-5 pb-5">
    <% @bookings.each do |booking| %>
      <div class="card-product m-2">
      <% if false %>
        <%= image_tag booking.tool.photo.key, width: 400, crop: :fill %>
      <% else %>
        <img src="https://images.unsplash.com/photo-1566937169390-7be4c63b8a0e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="booking" width="500">
      <% end %>
        <div class="card-product-infos">
          <h2><%= link_to booking.tool.name, booking_path(booking) %></h2>
          <p>from <%= booking.start_date %> to <%= booking.end_date %></p>
        </div>
      </div>
    <% end %>
  </div>

  <div class="mb-5"> <%= link_to 'Back to Homepage', root_path, class: "btn btn-tool" %></div>
</div>

app/views/bookings/show.html.erb
<div class="container" style=" padding-top: 80px">
  <h1 class="text-center mb-5">your tools are ready to be borrowed</h1>

  <div class="profile-card mb-5" style="display: flex;">
    <div style="width: 33%; height: 300px;" class="profile-pic">
        <% if @booking.tool.photo.attached? %>
          <%= cl_image_tag @booking.tool.photo.key, height: 200, crop: :fill, class: "text-center" %>
          <% else %>
          <img src="https://images.unsplash.com/photo-1566937169390-7be4c63b8a0e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="tool" width="500" class="text-center">
        <% end %>
    </div>
      <div style="width: 66%; height: 300px; padding-top: 20px;">
          <p style="font-size: 30px"> <strong><%= @booking.tool.name %></strong> </p>
          <p> <strong>Category:</strong> <%= @booking.tool.category %> </p>
          <% if current_user  %>
            <p> <strong>by:</strong> <%= @booking.tool.user.first_name %> <%= @booking.tool.user.last_name %></p>
          <% end %>
          <p> <strong>Description:</strong> <%= @booking.tool.description %> </p>
          <p> <strong>Start date:</strong> <%= @booking.start_date %> </p>
        <p> <strong>End date:</strong> <%= @booking.end_date %></p>
      </div>
  </div>
  <div class="row" style="display: flex;">
    <div class="container card p-5 text-center" style="width: 50%; height: 100%; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
     <h2 class="pb-4">What other people say about </br> <%= @booking.tool.name %></h2>
      <% if @booking.tool.reviews.empty? %>
        <p>Be the first to leave a review</p>
        <% else %>
          <ul class="list-group">
            <% @booking.tool.reviews.each do |review| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <%= review.content %>
                <span class="badge badge-primary badge-pill">
                  <% counter = 0 %>
                  <% 5.times do %>
                    <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
                    <% counter += 1 %>
                  <% end %>
                </span>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>

    <div class="container card p-5" style="width: 45%; height: 100%; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
       <h2 class="pb-4  text-center"> Share your opinion with others </h2>
        <%= simple_form_for ([@booking, @review]) do |f| %>
          <%= f.input :content, as: :text %>
          <%= f.input :rating, as: :integer%>
          <div class="text-center">
            <%= f.submit class: "btn btn-tool mt-5"  %>
          </div>
        <% end %>
      </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BorrowAppRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">
  </head>

  <body>

  <div class="page-container">
    <div class="navbar-container">
      <% if current_page?(root_path) %>
        <%= render "shared/navbar_home" %><%= render 'shared/flashes' %>
        <% else %>
        <%= render "shared/navbar" %><%= render 'shared/flashes' %>
      <% end %>
      </div>
    <div class="content-container"><%= yield %></div>
    <div class="footer-container"><%= render "shared/footer" %></div>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>


<div id="categories">

  <p class="mt-5">What type of tools do you need?</p>

  <div class="home-container">
    <div class="card-category" style="background-image: url(https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1540103711724-ebf833bde8d1%3Fixlib%3Drb-1.2.1%26ixid%3DeyJhcHBfaWQiOjEyMDd9%26auto%3Dformat%26fit%3Dcrop%26w%3D1055%26q%3D80)">
      DIY
    </div>
    <div class="card-category" style="background-image: url(https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1589051039495-eb77709c8268%3Fixlib%3Drb-1.2.1%26auto%3Dformat%26fit%3Dcrop%26w%3D934%26q%3D80)">
      Garden
    </div>

    <div class="card-category" style="background-image: url(https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1556910096-6f5e72db6803%3Fixlib%3Drb-1.2.1%26ixid%3DeyJhcHBfaWQiOjEyMDd9%26auto%3Dformat%26fit%3Dcrop%26w%3D1950%26q%3D80)">
      Kitchen
    </div>
  </div>

</div>
<!--
<div class="container" style="min-height: 100vh">
  <div class="row justify-content-center">

  </div>
</div>

 -->

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/shared/_banner.html.erb
<div class="banner">

  <div>
    <div>
      <h1>BORROW</h1>
    </div>

    <div>
      <p id="tools-tagline">get the tools you need when & where you need 'em</p>
      <p id="sub-tagline">no need to buy 'em</p>
    </div>

    <div id="search-bar">
      <%= form_tag tools_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "find 'em"
        %>
        <%= submit_tag "go", id: "search-button", class: "btn btn-tool" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <!-- <div class="footer-copyright">
    This footer was borrowed with <i class="fas fa-heart"></i> from Le Wagon
  </div> -->
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://www.flaticon.com/svg/static/icons/svg/2949/2949845.svg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active mr-3">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if false %>
          <%= image_tag current_user.photo.key, width: 50, height: 50, crop: :fill, class: "avatar", style: "width: auto" , id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
          <%= image_tag "https://www.flaticon.com/svg/static/icons/svg/1077/1077114.svg", class: "avatar" , id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
        <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Offer a tool", new_tool_path, class: "dropdown-item" %>
            <%= link_to "Rent a tool", tools_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_home.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-home fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://www.flaticon.com/svg/static/icons/svg/2949/2949845.svg" %>

    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active mr-3">
          <%= link_to "Home", root_path, class: "nav-link", style: "color:white"%>
        </li>
        <li class="nav-item dropdown">
          <% if false %>
          <%= image_tag current_user.photo.key, width: 50, height: 50, crop: :fill, class: "avatar", style: "width: auto" , id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
          <%= image_tag "https://www.flaticon.com/svg/static/icons/svg/1077/1077114.svg", class: "avatar" , id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
        <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Offer a tool", new_tool_path, class: "dropdown-item" %>
            <%= link_to "Rent a tool", tools_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tools/_info_window.html.erb
<%= link_to tool_path(tool), style:"text-decoration: none" do  %>
  <div class="card-marker">
    <% if tool.photo.attached? %>
    <%= cl_image_tag tool.photo.key, width: 400, crop: :fill %>
    <% else %>
    <img src="https://images.unsplash.com/photo-1566937169390-7be4c63b8a0e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="tool" width="500">
  <% end %>
    <div class="card-product-infos">
      <h2><%= tool.name %></h2>
      <p><%= tool.category %> | <%= tool.description %></p>
    </div>
  </div>
<% end %>

app/views/tools/create.html.erb
<h1>Tools#create</h1>
<p>Find me in app/views/tools/create.html.erb</p>

app/views/tools/index.html.erb
<div class="screen main-container">
  <div class="tools">
    <h2 class="mb-5 text-center">tools</h2>

    <% @tools.each do |tool| %>
      <%= link_to tool_path(tool), style:"text-decoration: none" do  %>
        <div class="card-product">
          <% if tool.photo.attached? %>
          <%= cl_image_tag tool.photo.key, width: 400, crop: :fill %>
          <% else %>
          <img src="https://images.unsplash.com/photo-1566937169390-7be4c63b8a0e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="tool" width="500">
        <% end %>
          <div class="card-product-infos">
            <h2><%= tool.name %></h2>
            <p><%= tool.category %> | <%= tool.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div id="map"
    style="width: 100vh; height: 100vh; margin-top: 85px"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>


</div>

<div class="text-center m-5"><%= link_to 'Back to Homepage', root_path, class: "btn btn-tool" %> </div>

app/views/tools/new.html.erb
<div class="screen">
  <h2 class= "mb-5">add a new tool</h2>

  <div class="card profile-card" style="width: 65%; height: 100%; box-shadow: 0 0 15px rgba(0,0,0,0.2); padding-left: 50px; padding-right: 50px; padding-top: 50px">
    <%= simple_form_for @tool do |f| %>
      <%= f.input :name %>
      <%= f.input :category, :collection => ['Manual DIY', 'Electrical DIY','Kitchen','Gardening'] %>
      <%= f.input :description %>
      <%= f.input :address %>
      <%= f.input :photo, as: :file %>
      <div class="text-center mt-5">
        <%= f.button :submit, class: "btn btn-flat mb-4"%>
      </div>
    <% end %>
  </div>

  <div class="m-5">
    <%= link_to 'Back to all tools', tools_path  %>
  </div>
</div>

app/views/tools/show.html.erb
<div class="screen">
  <h2 class="mb-5 text-center"> <%= @tool.name %> </h2>

  <div class="row justify-content-between mb-5" >
    <div class="card p-2 m-2" style="width: 30%; height: 100%; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
      <% if @tool.photo.attached? %>
        <%= cl_image_tag @tool.photo.key, height: 200, crop: :fill %>
        <% else %>
        <img src="https://images.unsplash.com/photo-1566937169390-7be4c63b8a0e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="tool" width="500">
      <% end %>
      <div class="card-body">
        <p> <strong>Category:</strong> <%= @tool.category %> </p>
        <% if current_user  %>
        <p> <strong>by:</strong> <%= @tool.user.first_name %> <%= @tool.user.last_name %></p>
        <p> <strong>Description:</strong> <%= @tool.description %> </p>
        <% end %>
      </div>
    </div>

    <div class="container card m-2 p-5" style="width: 65%; height: 350px; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
      <%= simple_form_for ([@tool, @booking]) do |f| %>
        <%= f.input :start_date, as: :date %>
        <%= f.input :end_date, as: :date %>
        <div class="text-center">
          <%= f.submit class: "btn btn-tool mb-5 mt-5"  %>
        </div>
      <% end %>
    </div>
  </div>

  <div id="map"
    style="width: 100%; height: 350px; box-shadow: 0 0 15px rgba(0,0,0,0.2);"
    data-markers="<%= @marker.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <div>
    <% unless @tool.reviews.empty? %>
      <div class="container card p-5 text-center" style="width: 100%; height: 100%; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
        <h2 class="pb-4">What other people say about </br> <%= @tool.name %></h2>
          <ul class="list-group">
            <% @tool.reviews.each do |review| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <%= review.content %>
                <span class="badge badge-primary badge-pill">
                  <% counter = 0 %>
                  <% 5.times do %>
                    <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
                    <% counter += 1 %>
                  <% end %>
                </span>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
  </div>
  <div class="text-center m-5"><%= link_to 'Back to all tools', tools_path, class: "btn btn-tool" %> </div>

</div>

app/views/users/edit.html.erb
<div class="container" style="min-height: 80vh; padding-top: 80px">
  <div class="card text-center profile-card mt-5 p-4" style="width: 20rem">
    <%= simple_form_for @user do |f| %>
      <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: "btn btn-flat mb-4"%>
    <% end %>
  </div>
  <div class="text-center pt-5">
    <%= link_to 'back to profile', user_path(@user) %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="screen">
  <div class="profile-info text-center p-2">
    <div class="card-body" style="d-flex flex-row">
      <h3 id="welcome-message">Welcome back</h3>
      <p id="user-name"><strong> <%= @user.first_name %> <%= @user.last_name %> </strong></p>
      <% if @user.photo.attached? %>
          <%= cl_image_tag @user.photo.key, width: 150, height: 150, crop: :fill, class: "rounded-circle" %>
          <% else %>
          <%= image_tag "https://www.flaticon.com/svg/static/icons/svg/1077/1077114.svg",  class: "avatar-large" %>
        <% end %>
        <div class="mt-4">
          <%= link_to 'Edit ✏️', edit_user_path(@user)  %>
        </div>
    </div>
  </div>


  <h2 class="mt-5">my tools</h2>
  <div class="card-bookings mb-5 mt-5">
    <% @user.tools.each do |tool| %>
        <div class="card-product m-2">
          <% if tool.photo.attached? %>
            <%= cl_image_tag tool.photo.key, width: 400, crop: :fill %>
            <% else %>
            <img src="https://images.unsplash.com/photo-1566937169390-7be4c63b8a0e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="booking" width="500">
          <% end %>
          <div class="card-product-infos">
            <h2><%= link_to tool.name, tool_path(tool) %> | <%= link_to '🗑', tool_path(tool), method: :delete, data:{confirm: 'Are you sure you want to delete this tool?', disable_with: 'Processing' } %></h2>
          </div>
        </div>
      <% end %>
  </div>


  <h2 class="mt-5">my bookings</h2>

  <div class="card-bookings mb-5 mt-5">
    <% @user.bookings.each do |booking| %>
      <div class="card-product m-2">
        <% if booking.tool.photo.attached? %>
        <%= cl_image_tag booking.tool.photo.key, width: 400, crop: :fill %>
        <% else %>
        <img src="https://images.unsplash.com/photo-1566937169390-7be4c63b8a0e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="booking" width="500">
      <% end %>
        <div class="card-product-infos">
          <h2><%= link_to booking.tool.name, booking_path(booking) %></h2>
          <p>from <%= booking.start_date %> to <%= booking.end_date %></p>
        </div>
      </div>
    <% end %>
  </div>

</div>